version: '3.4' # specify docker-compose version
 
# Define the services/containers to be run
services:
 client:
   build:
    context: .
    dockerfile: Dockerfile_client
   ports:
     - "4200:4200"
 server: # name of the first service
   build:
    context: .
    dockerfile: Dockerfile_server
   ports:
     - "3000:3000"
   environment:
     - MONGO_URL=mongodb+srv://usrnm:ufJshsUT6WwwnERi@cluster0.agrqbot.mongodb.net/?retryWrites=true&w=majority
